#!/bin/sh

PIDFILE='/opt/seerpod/run/actor.pid'

start() {
	echo "Starting Actor service...."
	PID=`nohup sh /opt/seerpod/scripts/system/actor.sh > /opt/seerpod/logs/actor.log 2>&1 & echo $!`
	if [ -z $PID ]; then
		printf "%s\n" "Actor service failed to start."
	else
		echo $PID > $PIDFILE
	        printf "%s\n" "Actor service started with PROCESS ID - $PID"
	fi
}

status() {
	if [ -f $PIDFILE ]; then
		PID=`cat $PIDFILE`
	        if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
	        	printf "%s\n" "Actor service dead but pidfile exists"
	        else
	        	echo "Actor service started with PROCESS ID - $PID"
	        fi
	else
	        printf "%s\n" "Actor service not running"
	fi
}

stop() {
        echo "Stopping Actor service..."
	PID=`cat $PIDFILE`
	if [ -f $PIDFILE ]; then
	        kill -HUP $PID
	        printf "%s\n" "Actor service stopped."
	        rm -f $PIDFILE
	else
		printf "%s\n" "Actor service pidfile not found"
	fi
}

case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    status)
	status
	exit 0
    ;;
    reload|restart|force-reload)
        stop
        start
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|status|reload|restart|force-reload}" 1>&2
        exit 1
    ;;
esac
